# -*- coding: utf-8 -*-
"""
Triangular, pentagonal, and hexagonal:
Problem 45
Published on 06 June 2003 at 06:00 pm [Server Time]
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import math

def is_pentagonal(number):
    return ((1 + math.sqrt(1 + 24 * number)) / 6.0).is_integer()


def is_hexagonal(number):
    return ((1 + math.sqrt(1 + 8 * number)) / 4.0).is_integer()



def get_tripenthexagonal():
    tri_number, diff, counter = 1, 1, 0
    
    while counter < 3:
        if is_pentagonal(tri_number) and is_hexagonal(tri_number):
            print tri_number
            counter += 1
        diff += 1
        tri_number += diff
    
    return None
    #return [n * (3 * n - 1) / 2 for n in range(1, goal)]

get_tripenthexagonal()